namespace Fonts
{
    // Glyph names and codepoints for FluentSystemIcons-Regular.ttf, originally generated by
    // IconFont2Code: https://andreinitescu.github.io/IconFont2Code
    //
    // Only the icons the app actually renders are kept. The full font is still shipped, so any
    // other glyph can be added back as a single line - paste the .ttf into the generator above,
    // find the icon, and copy its constant here.
    //
    // If you change the class to 'public' in order to use it outside its assembly
    //  you should also change the fields from 'const' to 'public static readonly'
    internal static class FluentUI
    {
        public const string FontFamily = "FluentUI";

        // All six are referenced from App.xaml as {x:Static f:FluentUI.<name>}.
        public const string arrow_clockwise_24_regular = "\uf13e";
        public const string arrow_download_24_regular = "\uf151";
        public const string desktop_24_regular = "\uf35a";
        public const string document_24_regular = "\uf379";
        public const string settings_24_regular = "\uf6aa";
        public const string table_settings_24_regular = "\uf777";
    }
}
